name: Reserve GCP CIDR in Infoblox

on:
  workflow_dispatch:
    inputs:
      network_view:
        description: "Infoblox Network View"
        type: string
        required: true
      supernet_cidr:
        description: "Supernet CIDR to reserve from (e.g., 10.0.0.0/16)"
        type: string
        required: true
      cidr_prefix:
        description: "CIDR Prefix Length (e.g., 24)"
        type: integer
        required: true
      subnet_name:
        description: "Subnet Name (Descriptive name for the subnet)"
        type: string
        required: true

jobs:
  reserve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_POOL }}
          service_account: ${{ secrets.GCP_SVC_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Get Infoblox Credentials
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          INFOBLOX_SECRET_NAME: ${{ secrets.INFOBLOX_SECRET_NAME }}
        run: python get_infoblox_secrets.py
      - name: Reserve CIDR in Infoblox
        id: reserve_cidr
        run: |
          python infoblox_ipam.py reserve \
            "${{ github.event.inputs.network_view }}" \
            "${{ github.event.inputs.supernet_cidr }}" \
            "${{ github.event.inputs.cidr_prefix }}" \
            "${{ github.event.inputs.subnet_name }}"
      - name: Output Reserved CIDR
        if: steps.reserve_cidr.outcome == 'success'
        run: |
          echo "Reserved CIDR: $(cat reserved_cidr.txt)"
          echo "Supernet CIDR: $(cat supernet_cidr.txt)"
          echo "Subnet Name: $(cat subnet_name.txt)"
          if [ -f "supernet_utilization.txt" ]; then
            echo "Supernet Utilization: $(cat supernet_utilization.txt)"
          fi
      - name: Output Error Message
        if: steps.reserve_cidr.outcome == 'failure'
        run: |
          echo "Error: $(cat error.txt)"
      - name: Create Approval Issue
        uses: actions/github-script@v7
        if: steps.reserve_cidr.outcome == 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `Reserved CIDR: $(cat reserved_cidr.txt)
Supernet CIDR: $(cat supernet_cidr.txt)
Subnet Name: $(cat subnet_name.txt)
            `;
            let issueBody = output;
            if (fs.existsSync('supernet_utilization.txt')) {
              issueBody += `
Supernet Utilization: $(cat supernet_utilization.txt)`;
            }
            issueBody += `
Please approve the CIDR reservation in Infoblox.  Comment "APPROVED" to proceed.`;

            const issueTitle = `Infoblox CIDR Reservation Request: $(cat reserved_cidr.txt)`;
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            });
            core.setOutput("issue_number", newIssue.data.number);
      - name: Wait for Approval
        uses: actions/github-script@v7
        if: steps.reserve_cidr.outcome == 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = core.getOutput("issue_number");
            console.log(`Waiting for approval on issue #${issueNumber}...`);
            let approved = false;
            for (let i = 0; i < 12; i++) { // Check for approval for up to 1 hour (12 * 5 minutes)
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
              });
              for (const comment of comments.data) {
                if (comment.body.toUpperCase().includes("APPROVED")) {
                  approved = true;
                  console.log("Approval received!");
                  break;
                }
              }
              if (approved) break;
              await new Promise(resolve => setTimeout(resolve, 300000)); // Wait 5 minutes
            }
            if (!approved) {
              core.setFailed(`Timed out waiting for approval on issue #${issueNumber}`);
            }